//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace trifenix.connect.agro.resources.dictionary.nums {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class num_placeholders {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal num_placeholders() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("trifenix.connect.agro.resources.dictionary.nums.num_placeholders", typeof(num_placeholders).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intervalo de días.
        /// </summary>
        public static string DAYS_INTERVAL {
            get {
                return ResourceManager.GetString("DAYS_INTERVAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número Correlativo.
        /// </summary>
        public static string GENERIC_CORRELATIVE {
            get {
                return ResourceManager.GetString("GENERIC_CORRELATIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horas de reingreso.
        /// </summary>
        public static string HOURS_TO_ENTRY {
            get {
                return ResourceManager.GetString("HOURS_TO_ENTRY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número de Plantas.
        /// </summary>
        public static string NUMBER_OF_PLANTS {
            get {
                return ResourceManager.GetString("NUMBER_OF_PLANTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número de Repetición.
        /// </summary>
        public static string NUMBER_OF_SECQUENTIAL_APPLICATION {
            get {
                return ResourceManager.GetString("NUMBER_OF_SECQUENTIAL_APPLICATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Año de plantación.
        /// </summary>
        public static string PLANTING_YEAR {
            get {
                return ResourceManager.GetString("PLANTING_YEAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Días de espera.
        /// </summary>
        public static string WAITING_DAYS {
            get {
                return ResourceManager.GetString("WAITING_DAYS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mojado Recomendado.
        /// </summary>
        public static string WETTING_RECOMMENDED {
            get {
                return ResourceManager.GetString("WETTING_RECOMMENDED", resourceCulture);
            }
        }
    }
}
