//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace trifenix.connect.agro.resources.dictionary.entities {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class entity_placeholders {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal entity_placeholders() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("trifenix.connect.agro.resources.dictionary.entities.entity_placeholders", typeof(entity_placeholders).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cuartel.
        /// </summary>
        public static string BARRACK {
            get {
                return ResourceManager.GetString("BARRACK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barrack.
        /// </summary>
        public static string BARRACK_EVENT {
            get {
                return ResourceManager.GetString("BARRACK_EVENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marca.
        /// </summary>
        public static string BRAND {
            get {
                return ResourceManager.GetString("BRAND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unidad de Negocios.
        /// </summary>
        public static string BUSINESSNAME {
            get {
                return ResourceManager.GetString("BUSINESSNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categoria Ingrediente.
        /// </summary>
        public static string CATEGORY_INGREDIENT {
            get {
                return ResourceManager.GetString("CATEGORY_INGREDIENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entidad Certificadora.
        /// </summary>
        public static string CERTIFIED_ENTITY {
            get {
                return ResourceManager.GetString("CERTIFIED_ENTITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Centro de Costos.
        /// </summary>
        public static string COSTCENTER {
            get {
                return ResourceManager.GetString("COSTCENTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dosis.
        /// </summary>
        public static string DOSES {
            get {
                return ResourceManager.GetString("DOSES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dosis en Orden.
        /// </summary>
        public static string DOSES_ORDER {
            get {
                return ResourceManager.GetString("DOSES_ORDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orden de Ejecución.
        /// </summary>
        public static string EXECUTION_ORDER {
            get {
                return ResourceManager.GetString("EXECUTION_ORDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estatus de Orden de ejecución.
        /// </summary>
        public static string EXECUTION_ORDER_STATUS {
            get {
                return ResourceManager.GetString("EXECUTION_ORDER_STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ubicación Geográfica.
        /// </summary>
        public static string GEOPOINT {
            get {
                return ResourceManager.GetString("GEOPOINT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingrediente.
        /// </summary>
        public static string INGREDIENT {
            get {
                return ResourceManager.GetString("INGREDIENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trabajo.
        /// </summary>
        public static string JOB {
            get {
                return ResourceManager.GetString("JOB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nebulizadora.
        /// </summary>
        public static string NEBULIZER {
            get {
                return ResourceManager.GetString("NEBULIZER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notificación de Evento.
        /// </summary>
        public static string NOTIFICATION_EVENT {
            get {
                return ResourceManager.GetString("NOTIFICATION_EVENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orden.
        /// </summary>
        public static string ORDER {
            get {
                return ResourceManager.GetString("ORDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carpeta de Pre-Ordenes.
        /// </summary>
        public static string ORDER_FOLDER {
            get {
                return ResourceManager.GetString("ORDER_FOLDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evento Fenológico.
        /// </summary>
        public static string PHENOLOGICAL_EVENT {
            get {
                return ResourceManager.GetString("PHENOLOGICAL_EVENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parcela.
        /// </summary>
        public static string PLOTLAND {
            get {
                return ResourceManager.GetString("PLOTLAND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polinizador.
        /// </summary>
        public static string POLLINATOR {
            get {
                return ResourceManager.GetString("POLLINATOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pre-Orden.
        /// </summary>
        public static string PREORDER {
            get {
                return ResourceManager.GetString("PREORDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Producto.
        /// </summary>
        public static string PRODUCT {
            get {
                return ResourceManager.GetString("PRODUCT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rol.
        /// </summary>
        public static string ROLE {
            get {
                return ResourceManager.GetString("ROLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raíz.
        /// </summary>
        public static string ROOTSTOCK {
            get {
                return ResourceManager.GetString("ROOTSTOCK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temporada.
        /// </summary>
        public static string SEASON {
            get {
                return ResourceManager.GetString("SEASON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sector.
        /// </summary>
        public static string SECTOR {
            get {
                return ResourceManager.GetString("SECTOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Especie.
        /// </summary>
        public static string SPECIE {
            get {
                return ResourceManager.GetString("SPECIE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Objetivo Aplicación.
        /// </summary>
        public static string TARGET {
            get {
                return ResourceManager.GetString("TARGET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tractor.
        /// </summary>
        public static string TRACTOR {
            get {
                return ResourceManager.GetString("TRACTOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario.
        /// </summary>
        public static string USER {
            get {
                return ResourceManager.GetString("USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variedad.
        /// </summary>
        public static string VARIETY {
            get {
                return ResourceManager.GetString("VARIETY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Espera Cosecha.
        /// </summary>
        public static string WAITINGHARVEST {
            get {
                return ResourceManager.GetString("WAITINGHARVEST", resourceCulture);
            }
        }
    }
}
