//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace trifenix.connect.agro.resources.dictionary.dates {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class date_snames {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal date_snames() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("trifenix.connect.agro.resources.dictionary.dates.date_snames", typeof(date_snames).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Termino.
        /// </summary>
        public static string END_DATE_EXECUTION_ORDER {
            get {
                return ResourceManager.GetString("END_DATE_EXECUTION_ORDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Termino.
        /// </summary>
        public static string END_DATE_ORDER {
            get {
                return ResourceManager.GetString("END_DATE_ORDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Termino.
        /// </summary>
        public static string END_DATE_PHENOLOGICAL_EVENT {
            get {
                return ResourceManager.GetString("END_DATE_PHENOLOGICAL_EVENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Termino.
        /// </summary>
        public static string END_DATE_SEASON {
            get {
                return ResourceManager.GetString("END_DATE_SEASON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ultima Modificación.
        /// </summary>
        public static string EXECUTION_ {
            get {
                return ResourceManager.GetString("EXECUTION_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inicio.
        /// </summary>
        public static string START_DATE_EXECUTION_ORDER {
            get {
                return ResourceManager.GetString("START_DATE_EXECUTION_ORDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inicio.
        /// </summary>
        public static string START_DATE_ORDER {
            get {
                return ResourceManager.GetString("START_DATE_ORDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inicio.
        /// </summary>
        public static string START_DATE_PHENOLOGICAL_EVENT {
            get {
                return ResourceManager.GetString("START_DATE_PHENOLOGICAL_EVENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inicio.
        /// </summary>
        public static string START_DATE_SEASON {
            get {
                return ResourceManager.GetString("START_DATE_SEASON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
    }
}
